<?php

namespace Proxies\__CG__\Ridwan\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VolunteerContactDetails extends \Ridwan\EntityBundle\Entity\VolunteerContactDetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'email', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'fax', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'streetNumber', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'street', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'city', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'divisionalSecretary', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'district', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'country', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'province', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'id', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'user');
        }

        return array('__isInitialized__', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'email', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'fax', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'streetNumber', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'street', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'city', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'divisionalSecretary', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'district', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'country', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'province', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'id', '' . "\0" . 'Ridwan\\EntityBundle\\Entity\\VolunteerContactDetails' . "\0" . 'user');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VolunteerContactDetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreetNumber($streetNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreetNumber', array($streetNumber));

        return parent::setStreetNumber($streetNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreetNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreetNumber', array());

        return parent::getStreetNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', array($street));

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', array());

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setDivisionalSecretary($divisionalSecretary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivisionalSecretary', array($divisionalSecretary));

        return parent::setDivisionalSecretary($divisionalSecretary);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivisionalSecretary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivisionalSecretary', array());

        return parent::getDivisionalSecretary();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrict($district)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrict', array($district));

        return parent::setDistrict($district);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrict', array());

        return parent::getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvince($province)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvince', array($province));

        return parent::setProvince($province);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvince', array());

        return parent::getProvince();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Ridwan\EntityBundle\Entity\VolunteerPersonal $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

}
