ridwan_opportunity_index:
    pattern:  /opportunities
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:index }
    
ridwan_opportunity_details:
    pattern:  /opportunitydetails/{opportunityID}
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:detail }
    
ridwan_opportunity_details_notification:
    pattern:  /opportunitydetails/{opportunityID}/{notificationID}
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:notification }
    
ridwan_opportunity_new:
    pattern:  /newopportunity
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:newopportunity }

    
ridwan_opportunity_completePage:
    pattern:  /feedbackopportunity/{opportunityID}
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:completePage }
    
ridwan_opportunity_complete:
    pattern:  /completeopportunity/{opportunityID}
    defaults: { _controller: RidwanOpportunityBundle:Opportunity:completeopportunity }
    methods: POST
    
