ridwan_profile:
    pattern:  /profile/{userID}
    defaults: { _controller: RidwanUserBundle:Profile:index }  
    
ridwan_account:
    pattern:  /account
    defaults: { _controller: RidwanUserBundle:Account:index }  
    
ridwan_profile_edit:
    pattern:  /editprofile
    defaults: { _controller: RidwanUserBundle:Profile:edit }  
    
ridwan_profile_picture:
    pattern:  /profilepicture
    defaults: { _controller: RidwanUserBundle:Profile:picture }

ridwan_user_volunteer_welcome:
    pattern: /volunteer/welcome
    defaults: {_controller: RidwanUserBundle:Volunteer:welcome}

ridwan_user_volunteer_education:
    pattern: /welcome/education
    defaults: {_controller: RidwanUserBundle:Volunteer:education}

ridwan_user_volunteer_employment:
    pattern: /welcome/employment
    defaults: {_controller: RidwanUserBundle:Volunteer:employment}

ridwan_user_volunteer_personal:
    pattern: /welcome/personal
    defaults: {_controller: RidwanUserBundle:Volunteer:personal}

ridwan_user_volunteer_skills:
    pattern: /welcome/skills
    defaults: {_controller: RidwanUserBundle:Volunteer:skills}

ridwan_user_volunteer_contacts:
    pattern: /welcome/contacts
    defaults: {_controller: RidwanUserBundle:Volunteer:contact}

ridwan_user_volunteer_referees:
    pattern: /welcome/referees
    defaults: {_controller: RidwanUserBundle:Volunteer:referees}

ridwan_user_volunteer_referee_add:
    pattern: /welcome/referee/add
    defaults: {_controller: RidwanUserBundle:Volunteer:Addreferee}
    methods: POST

ridwan_organization_welcome:
    pattern: /organization/welcome
    defaults: {_controller: RidwanUserBundle:Organization:welcome}

ridwan_organization_details:
    pattern: /organization/details
    defaults: {_controller: RidwanUserBundle:Organization:details}

ridwan_organization_contact:
    pattern: /organization/contact
    defaults: {_controller: RidwanUserBundle:Organization:contact}


